/*
  # Add Industry-Standard Warehouse Pricing Plans
  
  1. Pricing Plans Based on Storage Volume
    - Small Package Plan: Up to 100 cubic feet
    - Standard Plan: 100-500 cubic feet
    - Business Plan: 500-2000 cubic feet
    - Enterprise Plan: 2000+ cubic feet
    - Pallet Plan: Pallet-based storage
  
  2. Pricing matches industry standards (Amazon FBA, ShipBob, Red Stag)
*/

INSERT INTO warehouse_storage_plans (
  plan_name,
  plan_code,
  description,
  min_cubic_feet,
  max_cubic_feet,
  min_pallet_spaces,
  max_pallet_spaces,
  storage_fee_per_cubic_foot_monthly,
  storage_fee_per_pallet_monthly,
  receiving_fee_per_pallet,
  receiving_fee_per_unit,
  pick_pack_fee_per_item,
  handling_fee_percentage,
  minimum_monthly_fee,
  includes_insurance,
  includes_inventory_management,
  includes_reporting,
  priority_processing,
  dedicated_account_manager,
  is_active,
  display_order
) VALUES
(
  'Small Package Plan',
  'SMALL',
  'Perfect for small sellers and startups testing the market. Includes basic storage, receiving, and fulfillment services.',
  0,
  100,
  0,
  2,
  0.85,
  20.00,
  35.00,
  0.60,
  2.50,
  3.50,
  50.00,
  true,
  true,
  true,
  false,
  false,
  true,
  1
),
(
  'Standard Plan',
  'STANDARD',
  'Most popular plan for growing businesses. Competitive rates with full inventory management and reporting.',
  100,
  500,
  2,
  10,
  0.65,
  17.00,
  30.00,
  0.50,
  2.25,
  3.00,
  150.00,
  true,
  true,
  true,
  false,
  false,
  true,
  2
),
(
  'Business Plan',
  'BUSINESS',
  'Designed for established businesses with higher volume. Includes priority processing and better rates.',
  500,
  2000,
  10,
  40,
  0.50,
  15.00,
  25.00,
  0.40,
  2.00,
  2.50,
  300.00,
  true,
  true,
  true,
  true,
  false,
  true,
  3
),
(
  'Enterprise Plan',
  'ENTERPRISE',
  'Premium plan for large-scale operations. Best rates, dedicated account manager, and priority support.',
  2000,
  NULL,
  40,
  NULL,
  0.40,
  12.00,
  20.00,
  0.35,
  1.75,
  2.00,
  500.00,
  true,
  true,
  true,
  true,
  true,
  true,
  4
),
(
  'Pallet Plan',
  'PALLET',
  'Simple pallet-based pricing. Ideal for large items or bulk storage. Charged per pallet space used.',
  NULL,
  NULL,
  1,
  NULL,
  0.00,
  15.00,
  25.00,
  0.50,
  2.00,
  3.00,
  100.00,
  true,
  true,
  true,
  false,
  false,
  true,
  5
)
ON CONFLICT (plan_code) DO UPDATE SET
  plan_name = EXCLUDED.plan_name,
  description = EXCLUDED.description,
  min_cubic_feet = EXCLUDED.min_cubic_feet,
  max_cubic_feet = EXCLUDED.max_cubic_feet,
  min_pallet_spaces = EXCLUDED.min_pallet_spaces,
  max_pallet_spaces = EXCLUDED.max_pallet_spaces,
  storage_fee_per_cubic_foot_monthly = EXCLUDED.storage_fee_per_cubic_foot_monthly,
  storage_fee_per_pallet_monthly = EXCLUDED.storage_fee_per_pallet_monthly,
  receiving_fee_per_pallet = EXCLUDED.receiving_fee_per_pallet,
  receiving_fee_per_unit = EXCLUDED.receiving_fee_per_unit,
  pick_pack_fee_per_item = EXCLUDED.pick_pack_fee_per_item,
  handling_fee_percentage = EXCLUDED.handling_fee_percentage,
  minimum_monthly_fee = EXCLUDED.minimum_monthly_fee,
  includes_insurance = EXCLUDED.includes_insurance,
  includes_inventory_management = EXCLUDED.includes_inventory_management,
  includes_reporting = EXCLUDED.includes_reporting,
  priority_processing = EXCLUDED.priority_processing,
  dedicated_account_manager = EXCLUDED.dedicated_account_manager,
  is_active = EXCLUDED.is_active,
  display_order = EXCLUDED.display_order,
  updated_at = now();
