/*
  # Add Comfort Items & Pilgrimage Keepsakes

  1. Products Added
    - 5 comfort and support items for pilgrimage
    - 5 handmade keepsakes (non-symbolic)

  2. Category Placement
    - Comfort items: prayer-remembrance / prayer-mats-rugs
    - Keepsakes: sacred-space-home / home-objects

  3. Design Principles
    - Physical comfort supports spiritual practice
    - Keepsakes honor journey without becoming relics
    - Faith-neutral, suitable for all Abrahamic traditions
*/

INSERT INTO products (
  vendor_id,
  title,
  description,
  price,
  images,
  layer1_category_slug,
  layer2_category_slug,
  traditions,
  purposes,
  origin,
  materials,
  handmade_process,
  life_moments,
  use_contexts,
  practice_depth,
  time_to_make,
  purpose_description,
  artisan_info
) VALUES
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Travel Knee Support Mat',
  'Cushioned knee pad for prayer during pilgrimage. Lightweight, compressible. Essential for elderly pilgrims or those with joint concerns. Supports extended prayer without pain.',
  '32.99',
  ARRAY['https://images.pexels.com/photos/4188303/pexels-photo-4188303.jpeg'],
  'prayer-remembrance',
  'prayer-mats-rugs',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Prayer', 'Comfort', 'Travel', 'Health'],
  'Global',
  ARRAY['Memory Foam', 'Cotton Cover'],
  ARRAY['Handcrafted'],
  ARRAY['Pilgrimage', 'Daily Practice', 'Elderhood'],
  ARRAY['Travel', 'Prayer Space'],
  'Everyday Use',
  '3-5 days',
  'Created to enable prayer practice without physical discomfort during travel.',
  'Crafted with medical-grade foam and washable cover.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Foldable Sitting Cushion',
  'Travel meditation/prayer cushion. Supports proper posture during long prayer or study sessions. Folds flat for packing. Cross-tradition design.',
  '44.99',
  ARRAY['https://images.pexels.com/photos/4188303/pexels-photo-4188303.jpeg'],
  'prayer-remembrance',
  'prayer-mats-rugs',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Prayer', 'Reflection', 'Comfort', 'Travel'],
  'Global',
  ARRAY['Buckwheat Hulls', 'Cotton'],
  ARRAY['Handcrafted'],
  ARRAY['Pilgrimage', 'Daily Practice'],
  ARRAY['Travel', 'Prayer Space', 'Study Area'],
  'Dedicated Practice',
  '4-6 days',
  'Made to support comfortable, sustained sitting during spiritual practice.',
  'Handcrafted with organic fill and durable cotton casing.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Lightweight Wool Shawl',
  'Versatile wool shawl for pilgrimage. Provides warmth, modesty, or prayer covering. Natural fiber, travels light. Universal across Abrahamic traditions.',
  '54.99',
  ARRAY['https://images.pexels.com/photos/4188303/pexels-photo-4188303.jpeg'],
  'prayer-remembrance',
  'prayer-mats-rugs',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Prayer', 'Modesty', 'Comfort', 'Travel'],
  'Kashmir',
  ARRAY['Wool'],
  ARRAY['Hand-woven'],
  ARRAY['Pilgrimage', 'Daily Practice'],
  ARRAY['Travel', 'Prayer Space'],
  'Everyday Use',
  '7-10 days',
  'Designed as multi-purpose garment for sacred travel across climates.',
  'Hand-woven from Kashmir wool using traditional techniques.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Head & Shoulder Cover (Travel)',
  'Simple cotton head and shoulder covering. Lightweight, breathable. For modesty, sun protection, or prayer covering. Suitable across traditions.',
  '24.99',
  ARRAY['https://images.pexels.com/photos/4188303/pexels-photo-4188303.jpeg'],
  'prayer-remembrance',
  'prayer-mats-rugs',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Prayer', 'Modesty', 'Travel', 'Sun Protection'],
  'Global',
  ARRAY['Cotton'],
  ARRAY['Hand-woven'],
  ARRAY['Pilgrimage', 'Daily Practice'],
  ARRAY['Travel'],
  'Everyday Use',
  '2-4 days',
  'Created for practical and spiritual covering during pilgrimage.',
  'Hand-woven from breathable cotton for comfort in all climates.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Cold-Weather Prayer Wrap',
  'Insulated wrap for prayer in cold climates. Covers shoulders and arms. Allows free movement while providing warmth. Essential for winter pilgrimages.',
  '69.99',
  ARRAY['https://images.pexels.com/photos/4188303/pexels-photo-4188303.jpeg'],
  'prayer-remembrance',
  'prayer-mats-rugs',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Prayer', 'Comfort', 'Travel', 'Winter'],
  'Kashmir',
  ARRAY['Wool', 'Cotton Lining'],
  ARRAY['Hand-woven', 'Hand-stitched'],
  ARRAY['Pilgrimage', 'Daily Practice', 'Winter Prayer'],
  ARRAY['Travel', 'Prayer Space'],
  'Everyday Use',
  '7-10 days',
  'Made to enable cold-weather devotion without physical distress.',
  'Hand-woven and hand-stitched by Kashmir artisans for maximum warmth.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Olive Wood Travel Keepsake',
  'Small hand-carved olive wood piece. Smooth, pocket-sized. Holds memory of pilgrimage journey. No symbols, just natural wood beauty. Cross-tradition memento.',
  '19.99',
  ARRAY['https://images.pexels.com/photos/4188303/pexels-photo-4188303.jpeg'],
  'sacred-space-home',
  'home-objects',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Memory', 'Pilgrimage'],
  'Jerusalem',
  ARRAY['Olive Wood'],
  ARRAY['Hand-carved'],
  ARRAY['Pilgrimage'],
  ARRAY['Home'],
  'Everyday Use',
  '3-5 days',
  'Created to carry journey memories in natural, sacred wood.',
  'Hand-carved from Jerusalem olive wood by local artisans.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Hand-carved Wooden Token',
  'Simple wooden token with smooth finish. Carried during pilgrimage, kept as reminder. No inscriptions, no symbols. Personal meaning holder.',
  '14.99',
  ARRAY['https://images.pexels.com/photos/4188303/pexels-photo-4188303.jpeg'],
  'sacred-space-home',
  'home-objects',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Memory', 'Pilgrimage'],
  'Global',
  ARRAY['Wood'],
  ARRAY['Hand-carved'],
  ARRAY['Pilgrimage', 'Daily Practice'],
  ARRAY['Home', 'Travel'],
  'Everyday Use',
  '2-3 days',
  'Designed to hold personal meaning without imposing symbols.',
  'Hand-carved with care for smooth, comforting texture.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Papier-mâché Travel Box',
  'Small decorative box for pilgrimage mementos. Hand-painted, no religious imagery. Stores small keepsakes from sacred journey. Beautiful and functional.',
  '32.99',
  ARRAY['https://images.pexels.com/photos/4188303/pexels-photo-4188303.jpeg'],
  'sacred-space-home',
  'home-objects',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Memory', 'Organization', 'Beauty'],
  'Kashmir',
  ARRAY['Papier-mâché', 'Natural Pigments'],
  ARRAY['Handcrafted', 'Hand-painted'],
  ARRAY['Pilgrimage'],
  ARRAY['Home'],
  'Everyday Use',
  '7-10 days',
  'Made to beautifully preserve pilgrimage memories and small objects.',
  'Handcrafted using traditional Kashmir papier-mâché techniques.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Small Remembrance Object',
  'Simple ceramic or stone piece. Pocket or shelf size. Represents journey through form, not symbol. Honors pilgrimage without religious marking.',
  '22.99',
  ARRAY['https://images.pexels.com/photos/4188303/pexels-photo-4188303.jpeg'],
  'sacred-space-home',
  'home-objects',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Memory', 'Pilgrimage', 'Beauty'],
  'Global',
  ARRAY['Ceramic', 'Stone'],
  ARRAY['Handcrafted'],
  ARRAY['Pilgrimage'],
  ARRAY['Home', 'Prayer Space'],
  'Everyday Use',
  '3-5 days',
  'Created as abstract reminder of sacred journey and spiritual growth.',
  'Handcrafted with attention to form and tactile quality.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Journey Reflection Card Set',
  'Set of blank cards for recording pilgrimage reflections. One thought per card. Small enough to carry, meaningful enough to keep. Personal documentation tool.',
  '16.99',
  ARRAY['https://images.pexels.com/photos/4207892/pexels-photo-4207892.jpeg'],
  'sacred-space-home',
  'home-objects',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Reflection', 'Writing', 'Memory', 'Pilgrimage'],
  'Global',
  ARRAY['Cardstock', 'Recycled Paper'],
  ARRAY['Small Batch'],
  ARRAY['Pilgrimage'],
  ARRAY['Travel', 'Home'],
  'Dedicated Practice',
  '1-2 days',
  'Designed for capturing journey insights in portable, lasting format.',
  'Printed on quality cardstock for writing and long-term preservation.'
);
