/*
  # Add Travel Kits, Bundles & Carrying Items for Pilgrimage

  1. Products Added
    - 6 curated travel and pilgrimage kits
    - 6 carrying and protection items

  2. Category Placement
    - Kits/Bundles: gifts-collections / gift-sets-bundles
    - Carrying items: sacred-space-home / home-objects

  3. Design Principles
    - Functional bundles for complete travel readiness
    - Protective carrying for sacred items
    - Faith-neutral, suitable for all Abrahamic traditions
*/

INSERT INTO products (
  vendor_id,
  title,
  description,
  price,
  images,
  layer1_category_slug,
  layer2_category_slug,
  traditions,
  purposes,
  origin,
  materials,
  handmade_process,
  life_moments,
  use_contexts,
  practice_depth,
  time_to_make,
  purpose_description,
  artisan_info
) VALUES
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Pilgrimage Prayer Kit',
  'Complete kit for sacred travel: foldable mat, pocket prayer beads, direction compass, travel journal. Everything needed for prayer on the journey. Faith-neutral, works for all Abrahamic traditions.',
  '129.99',
  ARRAY['https://images.pexels.com/photos/4188303/pexels-photo-4188303.jpeg'],
  'gifts-collections',
  'gift-sets-bundles',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Prayer', 'Travel', 'Pilgrimage', 'Gifting'],
  'Global',
  ARRAY['Mixed Materials', 'Canvas Bag'],
  ARRAY['Handcrafted', 'Curated'],
  ARRAY['Pilgrimage', 'Gift'],
  ARRAY['Travel', 'Prayer Space'],
  'Dedicated Practice',
  '5-7 days',
  'Created to provide everything needed for faithful travel.',
  'Curated and assembled with items from multiple artisans.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Compact Travel Prayer Set',
  'Minimalist travel set: pocket mat, mini prayer beads, small compass. Fits in daypack. For pilgrims who travel light but pray faithfully.',
  '79.99',
  ARRAY['https://images.pexels.com/photos/4188303/pexels-photo-4188303.jpeg'],
  'gifts-collections',
  'gift-sets-bundles',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Prayer', 'Travel', 'Pilgrimage', 'Minimalism'],
  'Global',
  ARRAY['Mixed Materials', 'Cotton Pouch'],
  ARRAY['Handcrafted', 'Curated'],
  ARRAY['Pilgrimage', 'Daily Practice'],
  ARRAY['Travel'],
  'Everyday Use',
  '3-5 days',
  'Designed for minimalist travelers who maintain prayer practice.',
  'Carefully curated essentials in compact, travel-ready packaging.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Journey Reflection Kit',
  'Contemplative travel kit: journal, reflection cards, portable reading light, prayer cloth. For those who travel to reflect and deepen practice.',
  '94.99',
  ARRAY['https://images.pexels.com/photos/4207892/pexels-photo-4207892.jpeg'],
  'gifts-collections',
  'gift-sets-bundles',
  ARRAY['Abrahamic Shared', 'Christianity', 'Judaism', 'Islam'],
  ARRAY['Reflection', 'Travel', 'Writing', 'Contemplation'],
  'Global',
  ARRAY['Mixed Materials', 'Canvas Bag'],
  ARRAY['Handcrafted', 'Curated'],
  ARRAY['Pilgrimage', 'Daily Practice'],
  ARRAY['Travel', 'Study Area'],
  'Dedicated Practice',
  '5-7 days',
  'Made for reflective travelers seeking depth during journeys.',
  'Thoughtfully curated items supporting contemplative travel.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Night Practice Travel Kit',
  'For nighttime or dawn prayer while traveling: low-light mat, night vigil lamp, silent timer, small prayer book. Enables quiet devotion without disturbing others.',
  '109.99',
  ARRAY['https://images.pexels.com/photos/4207892/pexels-photo-4207892.jpeg'],
  'gifts-collections',
  'gift-sets-bundles',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Prayer', 'Night Vigil', 'Travel', 'Devotion'],
  'Global',
  ARRAY['Mixed Materials', 'Travel Case'],
  ARRAY['Handcrafted', 'Curated'],
  ARRAY['Pilgrimage', 'Night Vigil', 'Daily Practice'],
  ARRAY['Travel', 'Prayer Space'],
  'Dedicated Practice',
  '5-7 days',
  'Created for those who maintain nighttime or early morning practice while traveling.',
  'Curated specifically for low-light, quiet devotion in shared spaces.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Sacred Travel Essentials Bundle',
  'Core essentials for faithful travel: mat, beads, compass, water bottle holder, small towel. Practical items supporting spiritual journey.',
  '149.99',
  ARRAY['https://images.pexels.com/photos/4188303/pexels-photo-4188303.jpeg'],
  'gifts-collections',
  'gift-sets-bundles',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Prayer', 'Travel', 'Pilgrimage', 'Practical Care'],
  'Global',
  ARRAY['Mixed Materials', 'Canvas Bag'],
  ARRAY['Handcrafted', 'Curated'],
  ARRAY['Pilgrimage'],
  ARRAY['Travel'],
  'Everyday Use',
  '5-7 days',
  'Designed to support both spiritual and physical needs during pilgrimage.',
  'Comprehensive bundle combining prayer items with practical travel tools.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Minimalist Pilgrim Kit',
  'Ultra-light pilgrim essentials: pocket prayer cloth, 33-bead string, compass card. Fits in pocket. For those who walk with almost nothing.',
  '44.99',
  ARRAY['https://images.pexels.com/photos/4188303/pexels-photo-4188303.jpeg'],
  'gifts-collections',
  'gift-sets-bundles',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Prayer', 'Travel', 'Pilgrimage', 'Minimalism'],
  'Global',
  ARRAY['Mixed Materials', 'Cotton Pouch'],
  ARRAY['Handcrafted', 'Curated'],
  ARRAY['Pilgrimage', 'Daily Practice'],
  ARRAY['Travel'],
  'Everyday Use',
  '2-4 days',
  'Created for radical simplicity in sacred travel.',
  'Minimal, lightweight items chosen for maximum spiritual utility.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Hand-stitched Prayer Pouch',
  'Small embroidered pouch for prayer beads or small sacred items. Protects during travel. Drawstring closure, belt loop. Beautiful and functional.',
  '24.99',
  ARRAY['https://images.pexels.com/photos/4188303/pexels-photo-4188303.jpeg'],
  'sacred-space-home',
  'home-objects',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Organization', 'Travel', 'Protection'],
  'Levant',
  ARRAY['Cotton', 'Silk Thread'],
  ARRAY['Hand-stitched'],
  ARRAY['Pilgrimage', 'Daily Practice'],
  ARRAY['Travel', 'Home'],
  'Everyday Use',
  '3-5 days',
  'Made to protect prayer items with beauty and care.',
  'Hand-stitched by artisans using traditional embroidery patterns.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Travel Bead Pouch',
  'Soft velvet pouch for prayer beads. Cushioned to prevent damage. Small enough for pocket, secure enough for luggage. Protects sacred items during journey.',
  '18.99',
  ARRAY['https://images.pexels.com/photos/4188303/pexels-photo-4188303.jpeg'],
  'sacred-space-home',
  'home-objects',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Organization', 'Travel', 'Protection'],
  'Global',
  ARRAY['Velvet', 'Cotton Lining'],
  ARRAY['Handcrafted'],
  ARRAY['Pilgrimage', 'Daily Practice'],
  ARRAY['Travel', 'Home'],
  'Everyday Use',
  '2-3 days',
  'Designed to keep prayer beads safe and accessible during travel.',
  'Handcrafted with soft materials that protect without adding bulk.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Scripture Carry Sleeve',
  'Padded sleeve for small prayer books or scripture. Water-resistant exterior, soft interior. Fits in bag, protects sacred texts from travel wear.',
  '29.99',
  ARRAY['https://images.pexels.com/photos/4207892/pexels-photo-4207892.jpeg'],
  'sacred-space-home',
  'home-objects',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Study', 'Travel', 'Protection', 'Organization'],
  'Global',
  ARRAY['Cotton', 'Padding', 'Waterproof Lining'],
  ARRAY['Handcrafted'],
  ARRAY['Pilgrimage', 'Daily Practice'],
  ARRAY['Travel', 'Study Area'],
  'Everyday Use',
  '3-5 days',
  'Created to honor and protect sacred texts during journey.',
  'Handcrafted with care for both protection and reverence.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Foldable Prayer Mat Bag',
  'Custom bag designed for rolled or folded prayer mats. Shoulder strap, weather-resistant. Makes carrying mat easy and dignified.',
  '34.99',
  ARRAY['https://images.pexels.com/photos/4188303/pexels-photo-4188303.jpeg'],
  'sacred-space-home',
  'home-objects',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Travel', 'Organization', 'Protection'],
  'Global',
  ARRAY['Canvas', 'Cotton Strap'],
  ARRAY['Handcrafted'],
  ARRAY['Pilgrimage', 'Daily Practice'],
  ARRAY['Travel'],
  'Everyday Use',
  '3-5 days',
  'Made to make prayer mat carrying comfortable and respectful.',
  'Hand-sewn with durable materials and comfortable straps.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Small Travel Tote (Prayer Use)',
  'Compact tote designed for prayer items. Multiple interior pockets for organization. Understated design suitable for any tradition.',
  '39.99',
  ARRAY['https://images.pexels.com/photos/4188303/pexels-photo-4188303.jpeg'],
  'sacred-space-home',
  'home-objects',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Travel', 'Organization'],
  'Global',
  ARRAY['Canvas', 'Cotton'],
  ARRAY['Handcrafted'],
  ARRAY['Pilgrimage', 'Daily Practice'],
  ARRAY['Travel', 'Prayer Space'],
  'Everyday Use',
  '4-6 days',
  'Designed to keep all prayer items organized and accessible.',
  'Hand-sewn with thoughtful pocket placement for travel efficiency.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Drawstring Travel Bag',
  'Simple drawstring bag for prayer essentials. Lightweight, fits in larger luggage. Keeps sacred items separate and protected during journey.',
  '16.99',
  ARRAY['https://images.pexels.com/photos/4188303/pexels-photo-4188303.jpeg'],
  'sacred-space-home',
  'home-objects',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Travel', 'Organization', 'Protection'],
  'Global',
  ARRAY['Cotton', 'Cord'],
  ARRAY['Hand-stitched'],
  ARRAY['Pilgrimage', 'Daily Practice'],
  ARRAY['Travel'],
  'Everyday Use',
  '2-3 days',
  'Created for simple, lightweight organization of prayer items.',
  'Hand-stitched with durable materials and reinforced drawstring.'
);
