/*
  # Add Travel Prayer Tools & Direction Aids

  1. Products Added
    - 7 travel-sized prayer and remembrance tools
    - 6 direction and time awareness aids
    - All portable, designed for pilgrimage use

  2. Category Placement
    - Prayer tools: prayer-remembrance / prayer-beads-counters
    - Direction aids: prayer-remembrance / prayer-mats-rugs

  3. Design Principles
    - Compact and travel-ready
    - Support prayer rhythm during journeys
    - Faith-neutral, suitable for all Abrahamic traditions
*/

INSERT INTO products (
  vendor_id,
  title,
  description,
  price,
  images,
  layer1_category_slug,
  layer2_category_slug,
  traditions,
  purposes,
  origin,
  materials,
  handmade_process,
  life_moments,
  use_contexts,
  practice_depth,
  time_to_make,
  purpose_description,
  artisan_info
) VALUES
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Pocket Prayer Beads (Neutral)',
  'Small, simple prayer beads for travel. No religious symbols, just 33 smooth beads for counting. Fits in pocket, used across Abrahamic traditions for repetitive prayer or remembrance.',
  '19.99',
  ARRAY['https://images.pexels.com/photos/4188303/pexels-photo-4188303.jpeg'],
  'prayer-remembrance',
  'prayer-beads-counters',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Prayer', 'Remembrance', 'Travel', 'Pilgrimage'],
  'Jerusalem',
  ARRAY['Olive Wood'],
  ARRAY['Handcrafted'],
  ARRAY['Pilgrimage', 'Daily Practice'],
  ARRAY['Travel', 'Prayer Space'],
  'Everyday Use',
  '2-3 days',
  'Created for portable prayer counting during sacred journeys.',
  'Hand-carved from olive wood by Jerusalem artisans.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Mini Wooden Prayer Beads',
  'Compact wooden beads on durable cord. 33 beads for short prayers or decades. No markers, no symbols. Universal tool for repetitive devotion across all faiths.',
  '24.99',
  ARRAY['https://images.pexels.com/photos/4188303/pexels-photo-4188303.jpeg'],
  'prayer-remembrance',
  'prayer-beads-counters',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Prayer', 'Remembrance', 'Travel'],
  'Jerusalem',
  ARRAY['Olive Wood', 'Cotton Cord'],
  ARRAY['Handcrafted'],
  ARRAY['Pilgrimage', 'Daily Practice'],
  ARRAY['Travel', 'Prayer Space'],
  'Everyday Use',
  '2-4 days',
  'Made for travelers who practice repetitive prayer or contemplation.',
  'Handcrafted with attention to smooth texture and durability.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Travel Bead Counter (Manual)',
  'Mechanical counter with tactile click. No battery, no electronics. Helps track prayer repetitions during long journeys. Fits in palm.',
  '16.99',
  ARRAY['https://images.pexels.com/photos/5623016/pexels-photo-5623016.jpeg'],
  'prayer-remembrance',
  'prayer-beads-counters',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Prayer', 'Remembrance', 'Travel', 'Pilgrimage'],
  'Global',
  ARRAY['Metal', 'Plastic'],
  ARRAY['Small Batch'],
  ARRAY['Pilgrimage', 'Daily Practice'],
  ARRAY['Travel'],
  'Everyday Use',
  '1-2 days',
  'Designed for simple, reliable prayer counting without batteries.',
  'Assembled with durable mechanical components for long-term use.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Electronic Prayer Counter (Offline Travel)',
  'Battery-powered digital counter for travel. No connectivity, no tracking. Clips to clothing or bag. Lasts entire pilgrimage on single battery.',
  '22.99',
  ARRAY['https://images.pexels.com/photos/5623016/pexels-photo-5623016.jpeg'],
  'prayer-remembrance',
  'prayer-beads-counters',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Prayer', 'Remembrance', 'Travel', 'Pilgrimage'],
  'Global',
  ARRAY['Plastic', 'Electronic Components'],
  ARRAY['Small Batch'],
  ARRAY['Pilgrimage', 'Daily Practice'],
  ARRAY['Travel'],
  'Everyday Use',
  '2-3 days',
  'Created for accurate prayer counting during extended travel.',
  'Built with long battery life and travel-durable casing.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Mini Prayer Book (User-Supplied Text)',
  'Blank mini book for personal prayers. Pocket-sized, hand-bound. Fill with your own tradition prayers. Durable for travel, intimate for devotion.',
  '18.99',
  ARRAY['https://images.pexels.com/photos/4207892/pexels-photo-4207892.jpeg'],
  'prayer-remembrance',
  'prayer-beads-counters',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Prayer', 'Devotion', 'Travel', 'Writing'],
  'Global',
  ARRAY['Recycled Paper', 'Cotton Thread'],
  ARRAY['Hand-bound'],
  ARRAY['Pilgrimage', 'Daily Practice'],
  ARRAY['Travel', 'Prayer Space'],
  'Dedicated Practice',
  '3-5 days',
  'Made for carrying personal prayers during sacred journeys.',
  'Hand-bound with care for travel durability and prayer reverence.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Travel Scripture Cards (Blank/Neutral Prompts)',
  'Set of blank or lightly prompted cards for daily reflection. Small enough for pocket, meaningful enough for journey. Write your own verses or use prompts.',
  '14.99',
  ARRAY['https://images.pexels.com/photos/4207892/pexels-photo-4207892.jpeg'],
  'prayer-remembrance',
  'prayer-beads-counters',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Reflection', 'Study', 'Travel', 'Daily Wisdom'],
  'Global',
  ARRAY['Cardstock', 'Recycled Paper'],
  ARRAY['Small Batch'],
  ARRAY['Pilgrimage', 'Daily Practice'],
  ARRAY['Travel'],
  'Everyday Use',
  '1-2 days',
  'Designed for carrying daily wisdom during travel.',
  'Printed on quality cardstock with neutral, open-ended prompts.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Foldable Scripture Stand',
  'Collapsible book stand for travel. Holds books or tablets. Enables proper posture during prayer or study while traveling. Universal across traditions.',
  '27.99',
  ARRAY['https://images.pexels.com/photos/4207892/pexels-photo-4207892.jpeg'],
  'prayer-remembrance',
  'prayer-beads-counters',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Study', 'Prayer', 'Travel'],
  'Global',
  ARRAY['Wood', 'Metal Hinges'],
  ARRAY['Handcrafted'],
  ARRAY['Pilgrimage', 'Daily Practice'],
  ARRAY['Travel', 'Study Area'],
  'Everyday Use',
  '3-5 days',
  'Created for comfortable reading of sacred texts during travel.',
  'Handcrafted with collapsible design for easy packing.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Pocket Sacred Direction Compass',
  'Traditional brass compass for prayer orientation. Works worldwide, no battery. Fits in pocket, lasts lifetime. Essential for directional prayer in all Abrahamic faiths.',
  '29.99',
  ARRAY['https://images.pexels.com/photos/6253618/pexels-photo-6253618.jpeg'],
  'prayer-remembrance',
  'prayer-mats-rugs',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Prayer', 'Orientation', 'Travel', 'Pilgrimage'],
  'Global',
  ARRAY['Brass', 'Glass'],
  ARRAY['Handcrafted'],
  ARRAY['Pilgrimage', 'Daily Practice'],
  ARRAY['Travel'],
  'Everyday Use',
  '3-5 days',
  'Made for reliable prayer orientation during sacred journeys.',
  'Hand-assembled with traditional compass mechanics for accuracy.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Foldable Direction Indicator',
  'Collapsible direction pointer. Magnetic compass in compact housing. Sets up quickly for prayer. Universal tool for orientation across traditions.',
  '24.99',
  ARRAY['https://images.pexels.com/photos/6253618/pexels-photo-6253618.jpeg'],
  'prayer-remembrance',
  'prayer-mats-rugs',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Prayer', 'Orientation', 'Travel', 'Pilgrimage'],
  'Global',
  ARRAY['Plastic', 'Magnetic Compass'],
  ARRAY['Small Batch'],
  ARRAY['Pilgrimage', 'Daily Practice'],
  ARRAY['Travel'],
  'Everyday Use',
  '2-3 days',
  'Designed for quick, accurate prayer direction finding while traveling.',
  'Built for travel durability and ease of use.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Travel Prayer Time Card (Manual Reference)',
  'Pocket card with manual prayer time calculation guide. No automation, just reference. User calculates based on sunrise/sunset. Teaches time awareness.',
  '8.99',
  ARRAY['https://images.pexels.com/photos/4207892/pexels-photo-4207892.jpeg'],
  'prayer-remembrance',
  'prayer-mats-rugs',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Prayer', 'Time Management', 'Travel', 'Learning'],
  'Global',
  ARRAY['Laminated Cardstock'],
  ARRAY['Small Batch'],
  ARRAY['Pilgrimage', 'Daily Practice'],
  ARRAY['Travel'],
  'Everyday Use',
  '1 day',
  'Created to help travelers maintain prayer rhythm using local time.',
  'Designed with clear instructions for manual time calculation.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Manual Time Wheel (No Presets)',
  'Rotating wheel calculator for prayer times. Mechanical, no battery. User inputs sunrise, wheel calculates intervals. Educational and practical.',
  '34.99',
  ARRAY['https://images.pexels.com/photos/5623016/pexels-photo-5623016.jpeg'],
  'prayer-remembrance',
  'prayer-mats-rugs',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Prayer', 'Time Management', 'Travel', 'Learning'],
  'Global',
  ARRAY['Cardboard', 'Metal Brad'],
  ARRAY['Handcrafted'],
  ARRAY['Pilgrimage', 'Daily Practice'],
  ARRAY['Travel', 'Study Area'],
  'Dedicated Practice',
  '3-5 days',
  'Made for understanding and calculating sacred time intervals.',
  'Hand-assembled with precision printing and rotating mechanism.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Pocket Prayer Timer (Travel Version)',
  'Ultra-compact vibration timer. Silent alerts for prayer intervals. Battery lasts months. Clips to belt or pocket. Suitable for all Abrahamic time-based prayer.',
  '19.99',
  ARRAY['https://images.pexels.com/photos/5623016/pexels-photo-5623016.jpeg'],
  'prayer-remembrance',
  'prayer-mats-rugs',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Prayer', 'Time Management', 'Travel', 'Pilgrimage'],
  'Global',
  ARRAY['Plastic', 'Electronic Components'],
  ARRAY['Small Batch'],
  ARRAY['Pilgrimage', 'Daily Practice'],
  ARRAY['Travel'],
  'Everyday Use',
  '2-3 days',
  'Designed for discrete prayer time awareness during travel.',
  'Built for long battery life and compact portability.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Silent Interval Timer (Travel)',
  'Vibration-only interval timer. No sound, no light. Perfect for shared spaces during pilgrimage. Supports structured prayer or meditation practice.',
  '26.99',
  ARRAY['https://images.pexels.com/photos/5623016/pexels-photo-5623016.jpeg'],
  'prayer-remembrance',
  'prayer-mats-rugs',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Prayer', 'Reflection', 'Time Management', 'Travel'],
  'Global',
  ARRAY['Silicone', 'Electronic Components'],
  ARRAY['Small Batch'],
  ARRAY['Pilgrimage', 'Daily Practice'],
  ARRAY['Travel', 'Prayer Space'],
  'Dedicated Practice',
  '2-3 days',
  'Created for silent time tracking during group travel or shared spaces.',
  'Built with gentle vibration and travel-durable materials.'
);
