/*
  # Add Electronic Prayer Mats & Direction Devices

  1. Products Added
    - 7 electronic prayer mats
    - 5 direction and orientation devices

  2. Category Placement
    - Electronic Prayer Mats: prayer-remembrance / prayer-mats-rugs
    - Direction Devices: prayer-remembrance / prayer-mats-rugs

  3. Design Principles
    - Offline-first, no connectivity
    - Assist with prayer orientation without intrusiveness
    - Faith-neutral, suitable for all Abrahamic traditions
*/

INSERT INTO products (
  vendor_id,
  title,
  description,
  price,
  images,
  layer1_category_slug,
  layer2_category_slug,
  traditions,
  purposes,
  origin,
  materials,
  handmade_process,
  life_moments,
  use_contexts,
  practice_depth,
  time_to_make,
  purpose_description,
  artisan_info
) VALUES
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Orientation-Assisted Prayer Mat',
  'Prayer mat with built-in compass for accurate direction finding. Discrete indicators help with proper orientation. No sound, no light, just gentle guidance.',
  '89.99',
  ARRAY['https://images.pexels.com/photos/4188303/pexels-photo-4188303.jpeg'],
  'prayer-remembrance',
  'prayer-mats-rugs',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Prayer', 'Devotion'],
  'Global',
  ARRAY['Cotton', 'Wool', 'Electronic Compass'],
  ARRAY['Hand-woven', 'Hand-assembled'],
  ARRAY['Daily Practice'],
  ARRAY['Prayer Space', 'Travel'],
  'Dedicated Practice',
  '7-10 days',
  'Created for travelers and those needing accurate prayer orientation.',
  'Hand-woven mat with carefully integrated compass technology.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Compass-Integrated Prayer Mat',
  'Traditional woven mat with integrated electronic compass. Direction indicators embedded in design. Powered by long-lasting battery, completely offline.',
  '94.99',
  ARRAY['https://images.pexels.com/photos/4188303/pexels-photo-4188303.jpeg'],
  'prayer-remembrance',
  'prayer-mats-rugs',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity'],
  ARRAY['Prayer', 'Devotion'],
  'Anatolia',
  ARRAY['Cotton', 'Silk', 'Electronic Compass'],
  ARRAY['Hand-woven', 'Hand-assembled'],
  ARRAY['Daily Practice'],
  ARRAY['Prayer Space', 'Home'],
  'Dedicated Practice',
  '10-14 days',
  'Made for precise prayer orientation with traditional craftsmanship.',
  'Handcrafted in Anatolia with integrated compass technology.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Heated Comfort Prayer Mat',
  'Gently heated prayer mat for cold climates. Low-power heating element provides warmth without distraction. Temperature-controlled, battery-powered.',
  '129.99',
  ARRAY['https://images.pexels.com/photos/4188303/pexels-photo-4188303.jpeg'],
  'prayer-remembrance',
  'prayer-mats-rugs',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Prayer', 'Devotion', 'Comfort'],
  'Global',
  ARRAY['Wool', 'Cotton', 'Heating Element'],
  ARRAY['Hand-woven', 'Hand-assembled'],
  ARRAY['Daily Practice', 'Winter Prayer'],
  ARRAY['Prayer Space', 'Home'],
  'Everyday Use',
  '7-10 days',
  'Designed to support prayer practice in cold environments without discomfort.',
  'Hand-woven with safe, low-temperature heating technology.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Pressure-Neutral Electronic Prayer Mat',
  'Cushioned mat with electronic pressure distribution for comfort during long prayer sessions. No connectivity, just physical support.',
  '84.99',
  ARRAY['https://images.pexels.com/photos/4188303/pexels-photo-4188303.jpeg'],
  'prayer-remembrance',
  'prayer-mats-rugs',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Prayer', 'Devotion', 'Comfort'],
  'Global',
  ARRAY['Memory Foam', 'Cotton', 'Electronic Sensors'],
  ARRAY['Handcrafted', 'Hand-assembled'],
  ARRAY['Daily Practice'],
  ARRAY['Prayer Space', 'Home'],
  'Dedicated Practice',
  '5-7 days',
  'Created to support extended prayer without physical strain.',
  'Crafted with ergonomic materials and pressure-sensing technology.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Travel Electronic Prayer Mat',
  'Lightweight, foldable mat with integrated compass and storage pocket. Perfect for travelers. Offline, battery lasts months.',
  '69.99',
  ARRAY['https://images.pexels.com/photos/4188303/pexels-photo-4188303.jpeg'],
  'prayer-remembrance',
  'prayer-mats-rugs',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity'],
  ARRAY['Prayer', 'Devotion', 'Travel'],
  'Global',
  ARRAY['Polyester', 'Electronic Compass'],
  ARRAY['Small Batch'],
  ARRAY['Daily Practice', 'Pilgrimage'],
  ARRAY['Travel'],
  'Everyday Use',
  '3-5 days',
  'Made for maintaining prayer practice while traveling.',
  'Designed for durability and portability with integrated direction finding.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Foldable Orientation Prayer Mat',
  'Compact, foldable mat with electronic orientation marker. Fits in luggage, sets up in seconds. No apps, no connectivity.',
  '59.99',
  ARRAY['https://images.pexels.com/photos/4188303/pexels-photo-4188303.jpeg'],
  'prayer-remembrance',
  'prayer-mats-rugs',
  ARRAY['Abrahamic Shared', 'Islam'],
  ARRAY['Prayer', 'Travel'],
  'Global',
  ARRAY['Cotton', 'Electronic Compass'],
  ARRAY['Small Batch'],
  ARRAY['Daily Practice', 'Pilgrimage'],
  ARRAY['Travel', 'Prayer Space'],
  'Everyday Use',
  '2-4 days',
  'Designed for travelers needing quick, accurate prayer setup.',
  'Produced with travel-tested durability and simple electronics.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Minimalist Direction Indicator Mat',
  'Clean, minimal design with subtle direction indicators. E-ink display shows direction without glowing screen. Battery lasts over a year.',
  '74.99',
  ARRAY['https://images.pexels.com/photos/4188303/pexels-photo-4188303.jpeg'],
  'prayer-remembrance',
  'prayer-mats-rugs',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Prayer', 'Devotion'],
  'Global',
  ARRAY['Cotton', 'E-Ink Display', 'Electronic Compass'],
  ARRAY['Handcrafted', 'Hand-assembled'],
  ARRAY['Daily Practice'],
  ARRAY['Prayer Space', 'Home', 'Study Area'],
  'Dedicated Practice',
  '5-7 days',
  'Created for those seeking direction guidance without electronic distraction.',
  'Handcrafted with premium e-ink technology for long-term use.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Sacred Direction Finder',
  'Standalone compass device for prayer orientation. No frills, just accurate direction. Offline, no battery needed for basic function.',
  '34.99',
  ARRAY['https://images.pexels.com/photos/6253618/pexels-photo-6253618.jpeg'],
  'prayer-remembrance',
  'prayer-mats-rugs',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Prayer', 'Orientation'],
  'Global',
  ARRAY['Metal', 'Glass', 'Magnetic Compass'],
  ARRAY['Handcrafted'],
  ARRAY['Daily Practice', 'Pilgrimage'],
  ARRAY['Prayer Space', 'Travel'],
  'Everyday Use',
  '2-3 days',
  'Designed for simple, reliable prayer direction finding.',
  'Hand-assembled with precision compass mechanics.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Pocket Direction Compass',
  'Small, portable compass for prayer orientation. Fits in pocket, accurate worldwide. Traditional mechanism, no electronics needed.',
  '24.99',
  ARRAY['https://images.pexels.com/photos/6253618/pexels-photo-6253618.jpeg'],
  'prayer-remembrance',
  'prayer-mats-rugs',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Prayer', 'Orientation', 'Travel'],
  'Global',
  ARRAY['Brass', 'Glass'],
  ARRAY['Handcrafted'],
  ARRAY['Daily Practice', 'Pilgrimage'],
  ARRAY['Travel'],
  'Everyday Use',
  '1-2 days',
  'Created for travelers who need reliable direction finding anywhere.',
  'Hand-assembled with traditional compass craftsmanship.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Desk Direction Indicator',
  'Desktop compass device for prayer spaces. Always visible, always accurate. Elegant design complements any sacred space.',
  '44.99',
  ARRAY['https://images.pexels.com/photos/6253618/pexels-photo-6253618.jpeg'],
  'prayer-remembrance',
  'prayer-mats-rugs',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Prayer', 'Orientation'],
  'Global',
  ARRAY['Wood', 'Brass', 'Glass'],
  ARRAY['Handcrafted'],
  ARRAY['Daily Practice'],
  ARRAY['Prayer Space', 'Home', 'Study Area'],
  'Dedicated Practice',
  '3-5 days',
  'Made for permanent prayer spaces needing constant direction reference.',
  'Handcrafted with quality materials for lasting beauty and accuracy.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Travel Orientation Device',
  'Compact electronic compass with digital display. Shows accurate direction in any timezone. Offline, battery-powered.',
  '39.99',
  ARRAY['https://images.pexels.com/photos/6253618/pexels-photo-6253618.jpeg'],
  'prayer-remembrance',
  'prayer-mats-rugs',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity'],
  ARRAY['Prayer', 'Orientation', 'Travel'],
  'Global',
  ARRAY['Aluminum', 'Electronic Components'],
  ARRAY['Small Batch'],
  ARRAY['Daily Practice', 'Pilgrimage'],
  ARRAY['Travel'],
  'Everyday Use',
  '2-3 days',
  'Designed for reliable direction finding during travel and pilgrimage.',
  'Assembled with travel-tested electronics and durable casing.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Offline Direction Finder',
  'Simple electronic direction indicator. No GPS, no internet, just magnetic compass with digital readout. Battery lasts years.',
  '29.99',
  ARRAY['https://images.pexels.com/photos/6253618/pexels-photo-6253618.jpeg'],
  'prayer-remembrance',
  'prayer-mats-rugs',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Prayer', 'Orientation'],
  'Global',
  ARRAY['Plastic', 'Electronic Components'],
  ARRAY['Small Batch'],
  ARRAY['Daily Practice'],
  ARRAY['Prayer Space', 'Home', 'Travel'],
  'Everyday Use',
  '1-2 days',
  'Created for straightforward prayer orientation without complexity.',
  'Built with long-lasting battery and simple, reliable electronics.'
);
