/*
  # Add Prayer Timers, Sound Devices, and Light Devices

  1. Products Added
    - 7 prayer timers and rhythm devices
    - 5 sound and silence devices
    - 5 light and atmosphere devices

  2. Category Placement
    - Timers: prayer-remembrance / prayer-mats-rugs
    - Sound devices: reflection-inner-work / contemplative-tools
    - Light devices: sacred-space-home / sacred-lighting

  3. Design Principles
    - Offline-first, no connectivity
    - Support prayer rhythm without intrusiveness
    - Create atmosphere conducive to spiritual practice
*/

INSERT INTO products (
  vendor_id,
  title,
  description,
  price,
  images,
  layer1_category_slug,
  layer2_category_slug,
  traditions,
  purposes,
  origin,
  materials,
  handmade_process,
  life_moments,
  use_contexts,
  practice_depth,
  time_to_make,
  purpose_description,
  artisan_info
) VALUES
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Digital Prayer Interval Timer',
  'Programmable timer for structured prayer intervals. Silent countdown with gentle alert options. Battery-powered, completely offline.',
  '34.99',
  ARRAY['https://images.pexels.com/photos/5623016/pexels-photo-5623016.jpeg'],
  'prayer-remembrance',
  'prayer-mats-rugs',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Prayer', 'Remembrance', 'Time Management'],
  'Global',
  ARRAY['Plastic', 'Electronic Components'],
  ARRAY['Small Batch'],
  ARRAY['Daily Practice'],
  ARRAY['Prayer Space', 'Home', 'Study Area'],
  'Dedicated Practice',
  '2-3 days',
  'Created to support structured prayer rhythm throughout the day.',
  'Assembled with reliable timer components for consistent performance.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Silent Reflection Timer',
  'Vibration-only timer for meditation and contemplation. No sound, no light, just gentle haptic reminder. Pocket-sized.',
  '27.99',
  ARRAY['https://images.pexels.com/photos/5623016/pexels-photo-5623016.jpeg'],
  'reflection-inner-work',
  'contemplative-tools',
  ARRAY['Abrahamic Shared', 'Christianity', 'Judaism', 'Islam'],
  ARRAY['Reflection', 'Contemplation', 'Meditation'],
  'Global',
  ARRAY['Silicone', 'Electronic Components'],
  ARRAY['Small Batch'],
  ARRAY['Daily Practice'],
  ARRAY['Prayer Space', 'Home', 'Study Area'],
  'Dedicated Practice',
  '2-3 days',
  'Made for silent contemplation practice without auditory interruption.',
  'Designed with gentle vibration for respectful time awareness.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Countdown Prayer Timer',
  'Simple countdown device with large display. Set time, press start, focus on prayer. No complexity, just support.',
  '29.99',
  ARRAY['https://images.pexels.com/photos/5623016/pexels-photo-5623016.jpeg'],
  'prayer-remembrance',
  'prayer-mats-rugs',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Prayer', 'Devotion', 'Time Management'],
  'Global',
  ARRAY['Wood', 'Electronic Components'],
  ARRAY['Handcrafted'],
  ARRAY['Daily Practice'],
  ARRAY['Prayer Space', 'Home'],
  'Everyday Use',
  '3-4 days',
  'Designed for focused prayer sessions with clear time boundaries.',
  'Handcrafted with natural wood and simple electronics.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Dawn & Dusk Reminder Timer',
  'Automatic timer that tracks dawn and dusk based on manual sunset/sunrise input. Gentle reminder for traditional prayer times. No GPS, no internet.',
  '44.99',
  ARRAY['https://images.pexels.com/photos/5623016/pexels-photo-5623016.jpeg'],
  'prayer-remembrance',
  'prayer-mats-rugs',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Prayer', 'Devotion', 'Time Management'],
  'Global',
  ARRAY['Wood', 'Electronic Components'],
  ARRAY['Handcrafted'],
  ARRAY['Daily Practice'],
  ARRAY['Prayer Space', 'Home'],
  'Dedicated Practice',
  '4-6 days',
  'Created to support prayer at sacred times of day.',
  'Handcrafted with astronomical calculations built into offline timer.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Manual-Set Sacred Time Clock',
  'Traditional clock with prayer time markers. Set your own times, receive gentle reminders. No automation, just aid.',
  '39.99',
  ARRAY['https://images.pexels.com/photos/5623016/pexels-photo-5623016.jpeg'],
  'prayer-remembrance',
  'prayer-mats-rugs',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Prayer', 'Time Management'],
  'Global',
  ARRAY['Wood', 'Metal', 'Clock Mechanism'],
  ARRAY['Handcrafted'],
  ARRAY['Daily Practice'],
  ARRAY['Prayer Space', 'Home'],
  'Everyday Use',
  '5-7 days',
  'Made to integrate prayer rhythm into daily life visually.',
  'Handcrafted with traditional clock mechanics and prayer markers.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Desktop Rhythm Timer',
  'Elegant desktop timer for prayer and study sessions. Visible display, silent operation, manual control. No connectivity.',
  '49.99',
  ARRAY['https://images.pexels.com/photos/5623016/pexels-photo-5623016.jpeg'],
  'reflection-inner-work',
  'contemplative-tools',
  ARRAY['Abrahamic Shared', 'Christianity', 'Judaism', 'Islam'],
  ARRAY['Reflection', 'Study', 'Time Management'],
  'Global',
  ARRAY['Wood', 'Brass', 'Electronic Components'],
  ARRAY['Handcrafted'],
  ARRAY['Daily Practice'],
  ARRAY['Study Area', 'Prayer Space', 'Home'],
  'Dedicated Practice',
  '5-7 days',
  'Designed to support focused spiritual work with time awareness.',
  'Handcrafted with premium materials and quality timer components.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Travel Prayer Timer',
  'Compact, foldable timer for travelers. Multiple time zones, offline. Fits in luggage, battery lasts months.',
  '32.99',
  ARRAY['https://images.pexels.com/photos/5623016/pexels-photo-5623016.jpeg'],
  'prayer-remembrance',
  'prayer-mats-rugs',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity'],
  ARRAY['Prayer', 'Travel', 'Time Management'],
  'Global',
  ARRAY['Aluminum', 'Electronic Components'],
  ARRAY['Small Batch'],
  ARRAY['Daily Practice', 'Pilgrimage'],
  ARRAY['Travel'],
  'Everyday Use',
  '2-3 days',
  'Created for maintaining prayer rhythm while traveling.',
  'Built for durability and reliability in varied environments.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Electronic Silence Bell',
  'Gentle chime marker for transitions in contemplative practice. Single, pure tone. Volume adjustable, battery-powered.',
  '39.99',
  ARRAY['https://images.pexels.com/photos/6216589/pexels-photo-6216589.jpeg'],
  'reflection-inner-work',
  'contemplative-tools',
  ARRAY['Abrahamic Shared', 'Christianity', 'Judaism', 'Islam'],
  ARRAY['Reflection', 'Contemplation', 'Meditation'],
  'Global',
  ARRAY['Wood', 'Electronic Components', 'Speaker'],
  ARRAY['Handcrafted'],
  ARRAY['Daily Practice'],
  ARRAY['Prayer Space', 'Home', 'Study Area'],
  'Dedicated Practice',
  '4-6 days',
  'Made to mark sacred moments with respectful sound.',
  'Handcrafted with quality speaker for pure, gentle tone.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Digital Chime Marker',
  'Programmable chime for prayer or study intervals. Choice of natural sounds. Offline, no recordings of your practice.',
  '34.99',
  ARRAY['https://images.pexels.com/photos/6216589/pexels-photo-6216589.jpeg'],
  'reflection-inner-work',
  'contemplative-tools',
  ARRAY['Abrahamic Shared', 'Christianity', 'Judaism', 'Islam'],
  ARRAY['Reflection', 'Contemplation', 'Time Management'],
  'Global',
  ARRAY['Wood', 'Electronic Components'],
  ARRAY['Handcrafted'],
  ARRAY['Daily Practice'],
  ARRAY['Prayer Space', 'Study Area', 'Home'],
  'Dedicated Practice',
  '3-5 days',
  'Designed for gentle temporal markers during spiritual practice.',
  'Handcrafted with natural wood housing and quality audio components.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Soft-Tone Practice Bell',
  'Small bell with electronic amplification for shared spaces. Soft, non-intrusive tone. Volume control, battery-powered.',
  '29.99',
  ARRAY['https://images.pexels.com/photos/6216589/pexels-photo-6216589.jpeg'],
  'reflection-inner-work',
  'contemplative-tools',
  ARRAY['Abrahamic Shared', 'Christianity', 'Judaism'],
  ARRAY['Reflection', 'Contemplation'],
  'Global',
  ARRAY['Metal', 'Electronic Components'],
  ARRAY['Handcrafted'],
  ARRAY['Daily Practice'],
  ARRAY['Prayer Space', 'Home'],
  'Everyday Use',
  '2-4 days',
  'Created for gentle acoustic marking of practice transitions.',
  'Hand-assembled with traditional bell and modern amplification.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Interval Sound Marker',
  'Programmable interval marker with choice of tones. Supports structured practice sessions. Offline, private.',
  '32.99',
  ARRAY['https://images.pexels.com/photos/6216589/pexels-photo-6216589.jpeg'],
  'reflection-inner-work',
  'contemplative-tools',
  ARRAY['Abrahamic Shared', 'Christianity', 'Judaism', 'Islam'],
  ARRAY['Reflection', 'Meditation', 'Time Management'],
  'Global',
  ARRAY['Plastic', 'Electronic Components'],
  ARRAY['Small Batch'],
  ARRAY['Daily Practice'],
  ARRAY['Prayer Space', 'Study Area', 'Home'],
  'Dedicated Practice',
  '2-3 days',
  'Made to support rhythm and structure in contemplative work.',
  'Assembled with reliable electronics for consistent performance.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Breath-Pacing Sound Device',
  'Gentle sound pattern to support breath-focused prayer or meditation. Adjustable rhythm, offline operation.',
  '37.99',
  ARRAY['https://images.pexels.com/photos/6216589/pexels-photo-6216589.jpeg'],
  'reflection-inner-work',
  'contemplative-tools',
  ARRAY['Abrahamic Shared', 'Christianity', 'Judaism', 'Islam'],
  ARRAY['Reflection', 'Contemplation', 'Meditation'],
  'Global',
  ARRAY['Wood', 'Electronic Components', 'Speaker'],
  ARRAY['Handcrafted'],
  ARRAY['Daily Practice'],
  ARRAY['Prayer Space', 'Home'],
  'Dedicated Practice',
  '4-6 days',
  'Designed to support focused breathing during contemplative practice.',
  'Handcrafted with natural materials and gentle audio technology.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Fixed Warm Prayer Lamp',
  'Warm-toned LED lamp for prayer spaces. No dimming, no colors, just gentle warm light. Long-lasting, energy-efficient.',
  '54.99',
  ARRAY['https://images.pexels.com/photos/4207892/pexels-photo-4207892.jpeg'],
  'sacred-space-home',
  'sacred-lighting',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Sacred Space', 'Atmosphere'],
  'Global',
  ARRAY['Metal', 'Glass', 'LED'],
  ARRAY['Handcrafted'],
  ARRAY['Daily Practice'],
  ARRAY['Prayer Space', 'Home'],
  'Everyday Use',
  '5-7 days',
  'Created to provide consistent, respectful lighting for prayer.',
  'Handcrafted with warm LED technology for gentle illumination.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Timed Stillness Light',
  'Light that slowly dims over set time period. Supports timed meditation or prayer practice. Battery or plug-in.',
  '44.99',
  ARRAY['https://images.pexels.com/photos/4207892/pexels-photo-4207892.jpeg'],
  'sacred-space-home',
  'sacred-lighting',
  ARRAY['Abrahamic Shared', 'Christianity', 'Judaism', 'Islam'],
  ARRAY['Sacred Space', 'Atmosphere', 'Contemplation'],
  'Global',
  ARRAY['Ceramic', 'LED', 'Electronic Components'],
  ARRAY['Handcrafted'],
  ARRAY['Daily Practice'],
  ARRAY['Prayer Space', 'Home'],
  'Dedicated Practice',
  '5-7 days',
  'Made to mark practice duration through gradual light change.',
  'Handcrafted with smooth dimming technology for gentle transitions.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Night Vigil Lamp',
  'Ultra-low-light lamp for nighttime prayer or reading. Warm, gentle glow. Battery-powered, lasts weeks.',
  '39.99',
  ARRAY['https://images.pexels.com/photos/4207892/pexels-photo-4207892.jpeg'],
  'sacred-space-home',
  'sacred-lighting',
  ARRAY['Abrahamic Shared', 'Christianity', 'Judaism', 'Islam'],
  ARRAY['Sacred Space', 'Prayer', 'Night Vigil'],
  'Global',
  ARRAY['Wood', 'LED', 'Electronic Components'],
  ARRAY['Handcrafted'],
  ARRAY['Daily Practice', 'Night Vigil'],
  ARRAY['Prayer Space', 'Home'],
  'Dedicated Practice',
  '4-6 days',
  'Designed for nighttime devotion without disturbing sleep rhythms.',
  'Handcrafted with ultra-low brightness LED for gentle night use.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Desk Prayer Light',
  'Focused reading light for sacred texts. Adjustable arm, warm tone, no blue light. Energy-efficient LED.',
  '64.99',
  ARRAY['https://images.pexels.com/photos/4207892/pexels-photo-4207892.jpeg'],
  'sacred-space-home',
  'sacred-lighting',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Sacred Space', 'Study', 'Reading'],
  'Global',
  ARRAY['Metal', 'LED', 'Electronic Components'],
  ARRAY['Handcrafted'],
  ARRAY['Daily Practice'],
  ARRAY['Study Area', 'Prayer Space', 'Home'],
  'Everyday Use',
  '5-7 days',
  'Created to support focused study of sacred texts with proper lighting.',
  'Handcrafted with adjustable arm and eye-friendly LED technology.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Travel Stillness Lamp',
  'Portable lamp for prayer or meditation while traveling. Rechargeable battery, compact design. Warm, steady light.',
  '49.99',
  ARRAY['https://images.pexels.com/photos/4207892/pexels-photo-4207892.jpeg'],
  'sacred-space-home',
  'sacred-lighting',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Sacred Space', 'Travel', 'Atmosphere'],
  'Global',
  ARRAY['Aluminum', 'LED', 'Rechargeable Battery'],
  ARRAY['Small Batch'],
  ARRAY['Daily Practice', 'Pilgrimage'],
  ARRAY['Travel', 'Prayer Space'],
  'Everyday Use',
  '3-5 days',
  'Made for maintaining sacred space atmosphere while traveling.',
  'Built with durable materials and long-lasting rechargeable battery.'
);
