/*
  # Add Reading Devices, Travel Items, and Digital Products

  1. Products Added
    - 5 reading and text devices
    - 5 travel and portable practice devices
    - 12 digital-only products

  2. Category Placement
    - Reading devices: learning-scripture / study-aids
    - Travel devices: prayer-remembrance / prayer-mats-rugs
    - Digital products: gifts-collections / gift-sets-bundles

  3. Design Principles
    - E-readers are offline-first with no tracking
    - Travel items support practice on the move
    - Digital products have no physical fulfillment
*/

INSERT INTO products (
  vendor_id,
  title,
  description,
  price,
  images,
  layer1_category_slug,
  layer2_category_slug,
  traditions,
  purposes,
  origin,
  materials,
  handmade_process,
  life_moments,
  use_contexts,
  practice_depth,
  time_to_make,
  purpose_description,
  artisan_info
) VALUES
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'E-Ink Reflection Reader',
  'Dedicated e-ink device for sacred texts. No apps, no browser, no distractions. Just reading. Offline library storage, battery lasts weeks.',
  '149.99',
  ARRAY['https://images.pexels.com/photos/4207892/pexels-photo-4207892.jpeg'],
  'learning-scripture',
  'study-aids',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Study', 'Reading', 'Learning'],
  'Global',
  ARRAY['E-Ink Display', 'Aluminum', 'Electronic Components'],
  ARRAY['Small Batch'],
  ARRAY['Daily Practice'],
  ARRAY['Study Area', 'Home', 'Prayer Space'],
  'Dedicated Practice',
  '5-7 days',
  'Created for focused study of sacred texts without digital distraction.',
  'Assembled with premium e-ink display for comfortable extended reading.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Offline Scripture Reader',
  'Simple e-reader pre-loaded with public domain sacred texts. No internet, no tracking. Adjustable font, backlight for night reading.',
  '129.99',
  ARRAY['https://images.pexels.com/photos/4207892/pexels-photo-4207892.jpeg'],
  'learning-scripture',
  'study-aids',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Study', 'Reading', 'Learning'],
  'Global',
  ARRAY['E-Ink Display', 'Plastic', 'Electronic Components'],
  ARRAY['Small Batch'],
  ARRAY['Daily Practice'],
  ARRAY['Study Area', 'Home', 'Travel'],
  'Dedicated Practice',
  '4-6 days',
  'Made for accessing sacred texts anywhere without internet dependency.',
  'Pre-configured with open source texts and locked settings for focused reading.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Low-Light Reading Device',
  'E-reader optimized for low-light reading. Warm front light, no blue spectrum. Perfect for nighttime study or prayer.',
  '139.99',
  ARRAY['https://images.pexels.com/photos/4207892/pexels-photo-4207892.jpeg'],
  'learning-scripture',
  'study-aids',
  ARRAY['Abrahamic Shared', 'Christianity', 'Judaism', 'Islam'],
  ARRAY['Study', 'Reading', 'Night Vigil'],
  'Global',
  ARRAY['E-Ink Display', 'Electronic Components'],
  ARRAY['Small Batch'],
  ARRAY['Daily Practice', 'Night Vigil'],
  ARRAY['Study Area', 'Prayer Space', 'Home'],
  'Dedicated Practice',
  '5-7 days',
  'Designed for comfortable reading during nighttime study or devotion.',
  'Configured with warm lighting technology that respects natural sleep cycles.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Digital Text Display Stand',
  'Desktop stand with e-ink display for daily verses or prayers. Rechargeable, displays single passage for extended meditation.',
  '89.99',
  ARRAY['https://images.pexels.com/photos/4207892/pexels-photo-4207892.jpeg'],
  'learning-scripture',
  'study-aids',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Study', 'Contemplation', 'Daily Wisdom'],
  'Global',
  ARRAY['E-Ink Display', 'Wood', 'Electronic Components'],
  ARRAY['Handcrafted'],
  ARRAY['Daily Practice'],
  ARRAY['Prayer Space', 'Study Area', 'Home'],
  'Everyday Use',
  '5-7 days',
  'Created to keep daily wisdom visible for ongoing contemplation.',
  'Handcrafted with natural wood base and energy-efficient e-ink display.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Portable E-Ink Reader',
  'Pocket-sized e-reader for travel. Lightweight, durable, battery lasts months. Pre-loaded with public domain texts.',
  '99.99',
  ARRAY['https://images.pexels.com/photos/4207892/pexels-photo-4207892.jpeg'],
  'learning-scripture',
  'study-aids',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Study', 'Reading', 'Travel'],
  'Global',
  ARRAY['E-Ink Display', 'Plastic', 'Electronic Components'],
  ARRAY['Small Batch'],
  ARRAY['Daily Practice', 'Pilgrimage'],
  ARRAY['Travel', 'Study Area'],
  'Everyday Use',
  '3-5 days',
  'Made for accessing sacred texts during travel without carrying books.',
  'Built with travel-tested durability and long battery life.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Pocket Prayer Timer',
  'Ultra-compact timer fits on keychain. Silent vibration alerts. Battery lasts over a year. No connectivity.',
  '17.99',
  ARRAY['https://images.pexels.com/photos/5623016/pexels-photo-5623016.jpeg'],
  'prayer-remembrance',
  'prayer-mats-rugs',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity'],
  ARRAY['Prayer', 'Remembrance', 'Travel'],
  'Global',
  ARRAY['Plastic', 'Electronic Components'],
  ARRAY['Small Batch'],
  ARRAY['Daily Practice', 'Pilgrimage'],
  ARRAY['Travel'],
  'Everyday Use',
  '1-2 days',
  'Designed for prayer rhythm maintenance anywhere you go.',
  'Compact assembly with long-lasting battery and durable housing.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Portable Silence Bell',
  'Travel-sized electronic bell. Single gentle tone, volume adjustable. Fits in luggage, battery-powered.',
  '24.99',
  ARRAY['https://images.pexels.com/photos/6216589/pexels-photo-6216589.jpeg'],
  'reflection-inner-work',
  'contemplative-tools',
  ARRAY['Abrahamic Shared', 'Christianity', 'Judaism', 'Islam'],
  ARRAY['Reflection', 'Contemplation', 'Travel'],
  'Global',
  ARRAY['Metal', 'Electronic Components'],
  ARRAY['Small Batch'],
  ARRAY['Daily Practice', 'Pilgrimage'],
  ARRAY['Travel', 'Prayer Space'],
  'Everyday Use',
  '2-3 days',
  'Created for maintaining contemplative practice rituals while traveling.',
  'Built with compact design and reliable battery life.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Travel E-Ink Reader',
  'Slim e-reader designed for travel. Water-resistant, shock-proof. Pre-loaded with interfaith texts. No internet needed.',
  '119.99',
  ARRAY['https://images.pexels.com/photos/4207892/pexels-photo-4207892.jpeg'],
  'learning-scripture',
  'study-aids',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Study', 'Reading', 'Travel'],
  'Global',
  ARRAY['E-Ink Display', 'Waterproof Casing', 'Electronic Components'],
  ARRAY['Small Batch'],
  ARRAY['Daily Practice', 'Pilgrimage'],
  ARRAY['Travel'],
  'Everyday Use',
  '4-6 days',
  'Made for reliable access to sacred texts in any travel condition.',
  'Built with travel-grade protection and extended battery life.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Foldable Light Marker',
  'Collapsible LED reading light. Clips to books or stands alone. Warm tone, travel-friendly.',
  '19.99',
  ARRAY['https://images.pexels.com/photos/4207892/pexels-photo-4207892.jpeg'],
  'sacred-space-home',
  'sacred-lighting',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Study', 'Reading', 'Travel'],
  'Global',
  ARRAY['Plastic', 'LED', 'Electronic Components'],
  ARRAY['Small Batch'],
  ARRAY['Daily Practice', 'Pilgrimage'],
  ARRAY['Travel', 'Study Area'],
  'Everyday Use',
  '1-2 days',
  'Designed for reading sacred texts with proper lighting anywhere.',
  'Compact, lightweight design with energy-efficient LED.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Compact Direction Device',
  'Credit card sized electronic compass. Always in wallet, always available. Battery lasts years.',
  '14.99',
  ARRAY['https://images.pexels.com/photos/6253618/pexels-photo-6253618.jpeg'],
  'prayer-remembrance',
  'prayer-mats-rugs',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Prayer', 'Orientation', 'Travel'],
  'Global',
  ARRAY['Plastic', 'Electronic Components'],
  ARRAY['Small Batch'],
  ARRAY['Daily Practice', 'Pilgrimage'],
  ARRAY['Travel'],
  'Everyday Use',
  '1-2 days',
  'Created for convenient prayer orientation anywhere, anytime.',
  'Ultra-compact design with reliable long-lasting battery.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Digital Prayer Counter App License',
  'Offline prayer counting app. No tracking, no ads, no internet. One-time purchase, yours forever. iOS and Android.',
  '9.99',
  ARRAY['https://images.pexels.com/photos/5623016/pexels-photo-5623016.jpeg'],
  'gifts-collections',
  'gift-sets-bundles',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Prayer', 'Remembrance', 'Technology'],
  'Digital',
  ARRAY['Digital Software'],
  ARRAY['Digital'],
  ARRAY['Daily Practice'],
  ARRAY['Home', 'Travel', 'Prayer Space'],
  'Everyday Use',
  'Instant',
  'Digital app supporting offline prayer counting with complete privacy.',
  'Developed with privacy-first architecture and no data collection.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Digital Reflection Journal (PDF)',
  'Printable PDF journal for spiritual reflection. Structured prompts for daily contemplation. No subscription, lifetime access.',
  '14.99',
  ARRAY['https://images.pexels.com/photos/4207892/pexels-photo-4207892.jpeg'],
  'gifts-collections',
  'gift-sets-bundles',
  ARRAY['Abrahamic Shared', 'Christianity', 'Judaism', 'Islam'],
  ARRAY['Reflection', 'Contemplation', 'Writing'],
  'Digital',
  ARRAY['Digital PDF'],
  ARRAY['Digital'],
  ARRAY['Daily Practice'],
  ARRAY['Home', 'Study Area'],
  'Dedicated Practice',
  'Instant',
  'Created to support structured daily reflection practice.',
  'Thoughtfully designed prompts honoring interfaith contemplative traditions.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Digital Prayer Journal Template',
  'Customizable digital template for tracking prayer practice. Works offline in any word processor. One-time purchase.',
  '12.99',
  ARRAY['https://images.pexels.com/photos/4207892/pexels-photo-4207892.jpeg'],
  'gifts-collections',
  'gift-sets-bundles',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Prayer', 'Reflection', 'Organization'],
  'Digital',
  ARRAY['Digital Template'],
  ARRAY['Digital'],
  ARRAY['Daily Practice'],
  ARRAY['Home', 'Study Area'],
  'Everyday Use',
  'Instant',
  'Made for organized tracking of personal prayer journey.',
  'Simple, elegant design compatible with common software.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Guided Audio Reflection (MP3)',
  'Series of guided reflection sessions. Download, keep forever. No streaming, no tracking. 12 sessions, 20 minutes each.',
  '24.99',
  ARRAY['https://images.pexels.com/photos/6216589/pexels-photo-6216589.jpeg'],
  'gifts-collections',
  'gift-sets-bundles',
  ARRAY['Abrahamic Shared', 'Christianity', 'Judaism', 'Islam'],
  ARRAY['Reflection', 'Contemplation', 'Meditation'],
  'Digital',
  ARRAY['Digital Audio'],
  ARRAY['Digital'],
  ARRAY['Daily Practice'],
  ARRAY['Home', 'Prayer Space', 'Travel'],
  'Dedicated Practice',
  'Instant',
  'Designed for supported contemplative practice with gentle guidance.',
  'Recorded with care to honor multiple contemplative traditions.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Night & Dawn Listening Audio',
  'Peaceful audio for nighttime vigil or dawn prayer. Nature sounds, silence markers. Download and own. 8 tracks, 30-60 minutes each.',
  '19.99',
  ARRAY['https://images.pexels.com/photos/6216589/pexels-photo-6216589.jpeg'],
  'gifts-collections',
  'gift-sets-bundles',
  ARRAY['Abrahamic Shared', 'Christianity', 'Judaism', 'Islam'],
  ARRAY['Prayer', 'Contemplation', 'Night Vigil'],
  'Digital',
  ARRAY['Digital Audio'],
  ARRAY['Digital'],
  ARRAY['Daily Practice', 'Night Vigil'],
  ARRAY['Prayer Space', 'Home'],
  'Dedicated Practice',
  'Instant',
  'Created to support sacred time practice with atmospheric sound.',
  'Carefully composed to support without overwhelming prayer practice.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Digital Silence Timer App',
  'Minimalist timer app for meditation and prayer. Offline, no ads, no tracking. One purchase, lifetime updates.',
  '7.99',
  ARRAY['https://images.pexels.com/photos/5623016/pexels-photo-5623016.jpeg'],
  'gifts-collections',
  'gift-sets-bundles',
  ARRAY['Abrahamic Shared', 'Christianity', 'Judaism', 'Islam'],
  ARRAY['Reflection', 'Contemplation', 'Time Management'],
  'Digital',
  ARRAY['Digital Software'],
  ARRAY['Digital'],
  ARRAY['Daily Practice'],
  ARRAY['Prayer Space', 'Home', 'Travel'],
  'Everyday Use',
  'Instant',
  'Made for simple, distraction-free time awareness during practice.',
  'Built with minimal design philosophy and complete privacy.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Practice Tracker (Printable PDF)',
  'Annual practice tracking sheets. Print as needed, track daily habits. Simple, private, yours.',
  '8.99',
  ARRAY['https://images.pexels.com/photos/4207892/pexels-photo-4207892.jpeg'],
  'gifts-collections',
  'gift-sets-bundles',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Organization', 'Daily Wisdom', 'Growth'],
  'Digital',
  ARRAY['Digital PDF'],
  ARRAY['Digital'],
  ARRAY['Daily Practice'],
  ARRAY['Home', 'Study Area'],
  'Everyday Use',
  'Instant',
  'Designed for visual tracking of spiritual practice consistency.',
  'Clean, printable format for personal record keeping.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Digital Sacred Calendar',
  'Interfaith calendar marking sacred days across traditions. PDF format, print or view digitally. Updated annually.',
  '11.99',
  ARRAY['https://images.pexels.com/photos/4207892/pexels-photo-4207892.jpeg'],
  'gifts-collections',
  'gift-sets-bundles',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Organization', 'Learning', 'Interfaith Understanding'],
  'Digital',
  ARRAY['Digital PDF'],
  ARRAY['Digital'],
  ARRAY['Daily Practice'],
  ARRAY['Home', 'Study Area'],
  'Everyday Use',
  'Instant',
  'Created to support awareness of sacred rhythms across traditions.',
  'Researched and compiled with respect for multiple faith calendars.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Downloadable Study Planner',
  'Digital planner for scripture study. Track progress, set goals, reflect. Works offline in any PDF reader.',
  '13.99',
  ARRAY['https://images.pexels.com/photos/4207892/pexels-photo-4207892.jpeg'],
  'gifts-collections',
  'gift-sets-bundles',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Study', 'Organization', 'Learning'],
  'Digital',
  ARRAY['Digital PDF'],
  ARRAY['Digital'],
  ARRAY['Daily Practice'],
  ARRAY['Study Area', 'Home'],
  'Dedicated Practice',
  'Instant',
  'Made for structured, intentional sacred text study.',
  'Designed to support long-term learning and reflection habits.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Digital Gift Card',
  'Electronic gift card for platform purchases. Delivered via email, redeemable anytime. No expiration.',
  '25.00',
  ARRAY['https://images.pexels.com/photos/4207892/pexels-photo-4207892.jpeg'],
  'gifts-collections',
  'gift-sets-bundles',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Gifting', 'Generosity'],
  'Digital',
  ARRAY['Digital Gift Card'],
  ARRAY['Digital'],
  ARRAY['Gift'],
  ARRAY['Gift'],
  'Everyday Use',
  'Instant',
  'Created for thoughtful gifting of spiritual practice items.',
  'Delivered instantly with personalized message option.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Audio Library Access (Annual)',
  'One year access to curated audio library. Reflections, prayers, sacred music. Download or stream. No ads, no tracking.',
  '39.99',
  ARRAY['https://images.pexels.com/photos/6216589/pexels-photo-6216589.jpeg'],
  'gifts-collections',
  'gift-sets-bundles',
  ARRAY['Abrahamic Shared', 'Christianity', 'Judaism', 'Islam'],
  ARRAY['Reflection', 'Contemplation', 'Learning'],
  'Digital',
  ARRAY['Digital Subscription'],
  ARRAY['Digital'],
  ARRAY['Daily Practice'],
  ARRAY['Home', 'Prayer Space', 'Travel'],
  'Dedicated Practice',
  'Instant',
  'Designed for year-round access to contemplative audio resources.',
  'Curated collection honoring multiple spiritual traditions.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Annual Digital Practice Subscription',
  'Year-long subscription: monthly reflection guides, prayer journals, sacred calendars. Download and keep. No DRM.',
  '49.99',
  ARRAY['https://images.pexels.com/photos/4207892/pexels-photo-4207892.jpeg'],
  'gifts-collections',
  'gift-sets-bundles',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Reflection', 'Study', 'Organization'],
  'Digital',
  ARRAY['Digital Subscription'],
  ARRAY['Digital'],
  ARRAY['Daily Practice'],
  ARRAY['Home', 'Study Area', 'Prayer Space'],
  'Dedicated Practice',
  'Instant',
  'Created for sustained support of daily spiritual practice throughout the year.',
  'Thoughtfully designed resources delivered monthly, yours to keep forever.'
);
