/*
  # Add Electronic Prayer Counters & Digital Counting Devices

  1. Products Added
    - 13 electronic prayer counters and digital counting devices
    - Including finger counters, ring counters, handheld devices, and electronic bead counters

  2. Category Placement
    - Layer 1: prayer-remembrance
    - Layer 2: prayer-beads-counters

  3. Design Principles
    - Offline-first, no tracking, no connectivity
    - Faith-neutral design
    - Supports counting practice across all Abrahamic traditions
*/

INSERT INTO products (
  vendor_id,
  title,
  description,
  price,
  images,
  layer1_category_slug,
  layer2_category_slug,
  traditions,
  purposes,
  origin,
  materials,
  handmade_process,
  life_moments,
  use_contexts,
  practice_depth,
  time_to_make,
  purpose_description,
  artisan_info
) VALUES
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Electronic Finger Prayer Counter',
  'Discreet finger-mounted electronic counter for silent prayer counting. Single-button operation with clear digital display. Completely offline with no connectivity.',
  '24.99',
  ARRAY['https://images.pexels.com/photos/5623016/pexels-photo-5623016.jpeg'],
  'prayer-remembrance',
  'prayer-beads-counters',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Prayer', 'Remembrance', 'Devotion'],
  'Global',
  ARRAY['Silicone', 'Electronic Components'],
  ARRAY['Handcrafted'],
  ARRAY['Daily Practice'],
  ARRAY['Prayer Space', 'Travel'],
  'Everyday Use',
  '2-3 days',
  'Created to support quiet, focused prayer counting without distraction.',
  'Produced in small batches with quality electronic components.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Ring-Style Electronic Prayer Counter',
  'Elegant ring design with built-in digital counter. Discrete touch interface allows counting without drawing attention. Perfect for continuous remembrance practice.',
  '34.99',
  ARRAY['https://images.pexels.com/photos/6253618/pexels-photo-6253618.jpeg'],
  'prayer-remembrance',
  'prayer-beads-counters',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Prayer', 'Remembrance'],
  'Global',
  ARRAY['Metal', 'Electronic Components'],
  ARRAY['Handcrafted'],
  ARRAY['Daily Practice'],
  ARRAY['Prayer Space', 'Travel', 'Home'],
  'Everyday Use',
  '3-4 days',
  'Made for uninterrupted remembrance practice throughout the day.',
  'Carefully assembled by skilled technicians with attention to comfort and durability.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Handheld Digital Bead Counter',
  'Palm-sized digital counting device with tactile button interface. Large, easy-to-read display. Battery lasts months with daily use. No connectivity, no tracking.',
  '29.99',
  ARRAY['https://images.pexels.com/photos/5623016/pexels-photo-5623016.jpeg'],
  'prayer-remembrance',
  'prayer-beads-counters',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Prayer', 'Remembrance', 'Devotion'],
  'Global',
  ARRAY['Plastic', 'Electronic Components'],
  ARRAY['Small Batch'],
  ARRAY['Daily Practice'],
  ARRAY['Prayer Space', 'Home', 'Study Area'],
  'Dedicated Practice',
  '2-3 days',
  'Designed for daily prayer rhythm and counting practice.',
  'Produced with reliable components for long-term spiritual practice.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Clip-on Prayer Counter',
  'Lightweight counter that clips onto clothing or prayer items. Silent operation with gentle vibration feedback. Resets easily between prayer sessions.',
  '19.99',
  ARRAY['https://images.pexels.com/photos/5623016/pexels-photo-5623016.jpeg'],
  'prayer-remembrance',
  'prayer-beads-counters',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity'],
  ARRAY['Prayer', 'Remembrance'],
  'Global',
  ARRAY['Plastic', 'Metal Clip', 'Electronic Components'],
  ARRAY['Small Batch'],
  ARRAY['Daily Practice'],
  ARRAY['Prayer Space', 'Travel'],
  'Everyday Use',
  '1-2 days',
  'Created for portable prayer practice without carrying extra items.',
  'Assembled with care for lightweight durability.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Silent Vibration Prayer Counter',
  'Vibration-only counter with no display or sound. Counts through gentle haptic feedback. Ideal for shared prayer spaces or nighttime devotion.',
  '27.99',
  ARRAY['https://images.pexels.com/photos/5623016/pexels-photo-5623016.jpeg'],
  'prayer-remembrance',
  'prayer-beads-counters',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Prayer', 'Remembrance', 'Contemplation'],
  'Global',
  ARRAY['Silicone', 'Electronic Components'],
  ARRAY['Handcrafted'],
  ARRAY['Daily Practice', 'Night Vigil'],
  ARRAY['Prayer Space', 'Home'],
  'Dedicated Practice',
  '2-3 days',
  'Made to support silent prayer without visual distraction.',
  'Carefully calibrated for gentle, respectful feedback.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Resettable Electronic Tally Counter',
  'Simple, robust counting device with large reset button. No frills, just reliable counting. Built to last years of daily practice.',
  '22.99',
  ARRAY['https://images.pexels.com/photos/5623016/pexels-photo-5623016.jpeg'],
  'prayer-remembrance',
  'prayer-beads-counters',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Prayer', 'Remembrance'],
  'Global',
  ARRAY['Metal', 'Electronic Components'],
  ARRAY['Small Batch'],
  ARRAY['Daily Practice'],
  ARRAY['Prayer Space', 'Study Area', 'Home'],
  'Everyday Use',
  '1-2 days',
  'Designed for straightforward, distraction-free prayer counting.',
  'Built with durable components for long-term reliability.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Minimal Display Prayer Counter (E-Ink)',
  'Ultra-low power e-ink display counter. Battery lasts up to one year. Gentle on the eyes, no backlight distraction. Offline and private.',
  '44.99',
  ARRAY['https://images.pexels.com/photos/5623016/pexels-photo-5623016.jpeg'],
  'prayer-remembrance',
  'prayer-beads-counters',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Prayer', 'Remembrance', 'Contemplation'],
  'Global',
  ARRAY['E-Ink Display', 'Electronic Components'],
  ARRAY['Handcrafted'],
  ARRAY['Daily Practice'],
  ARRAY['Prayer Space', 'Study Area', 'Home'],
  'Dedicated Practice',
  '4-5 days',
  'Created for long-term practice with minimal maintenance and no digital distraction.',
  'Assembled with premium e-ink technology for extended battery life.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Mechanical-Digital Hybrid Counter',
  'Combines satisfying mechanical click with digital display. Tactile feedback honors traditional counting while offering modern convenience.',
  '39.99',
  ARRAY['https://images.pexels.com/photos/5623016/pexels-photo-5623016.jpeg'],
  'prayer-remembrance',
  'prayer-beads-counters',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Prayer', 'Remembrance'],
  'Global',
  ARRAY['Metal', 'Electronic Components', 'Mechanical Parts'],
  ARRAY['Hand-assembled'],
  ARRAY['Daily Practice'],
  ARRAY['Prayer Space', 'Home', 'Study Area'],
  'Dedicated Practice',
  '4-6 days',
  'Made to bridge traditional tactile prayer practice with modern counting accuracy.',
  'Hand-assembled with precision mechanical and electronic components.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Electronic Bead Counter Loop',
  'Bead-style loop with integrated electronic counting. Each bead press registers digitally. Combines familiar form with modern tracking.',
  '49.99',
  ARRAY['https://images.pexels.com/photos/5623016/pexels-photo-5623016.jpeg'],
  'prayer-remembrance',
  'prayer-beads-counters',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Prayer', 'Remembrance', 'Devotion'],
  'Global',
  ARRAY['Wood', 'Electronic Components', 'Natural Beads'],
  ARRAY['Hand-assembled'],
  ARRAY['Daily Practice'],
  ARRAY['Prayer Space', 'Home', 'Travel'],
  'Dedicated Practice',
  '5-7 days',
  'Created to honor traditional bead prayer while offering count verification.',
  'Hand-assembled with natural materials and embedded electronics.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Digital Bead String Counter',
  'String of counting beads with digital display at end. Tactile prayer experience with automatic count tracking. Offline, no data collection.',
  '42.99',
  ARRAY['https://images.pexels.com/photos/5623016/pexels-photo-5623016.jpeg'],
  'prayer-remembrance',
  'prayer-beads-counters',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Prayer', 'Remembrance'],
  'Global',
  ARRAY['Wood', 'Electronic Components', 'Cord'],
  ARRAY['Handcrafted'],
  ARRAY['Daily Practice'],
  ARRAY['Prayer Space', 'Travel', 'Home'],
  'Dedicated Practice',
  '5-7 days',
  'Made for those who love bead prayer but want count certainty.',
  'Handcrafted with sustainably sourced beads and quality electronics.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Electronic Wrist Bead Counter',
  'Wearable bead bracelet with discrete digital counter. Each bead rotation registers electronically. Prayer on the go.',
  '36.99',
  ARRAY['https://images.pexels.com/photos/5623016/pexels-photo-5623016.jpeg'],
  'prayer-remembrance',
  'prayer-beads-counters',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity'],
  ARRAY['Prayer', 'Remembrance'],
  'Global',
  ARRAY['Wood', 'Electronic Components', 'Elastic Cord'],
  ARRAY['Handcrafted'],
  ARRAY['Daily Practice'],
  ARRAY['Travel', 'Home'],
  'Everyday Use',
  '3-5 days',
  'Designed for continuous remembrance throughout daily activities.',
  'Handcrafted with attention to comfort and unobtrusive design.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Touch-Increment Bead Counter',
  'Touch-sensitive counting device shaped like a prayer bead. No buttons, just gentle touch. Silent, private, respectful.',
  '32.99',
  ARRAY['https://images.pexels.com/photos/5623016/pexels-photo-5623016.jpeg'],
  'prayer-remembrance',
  'prayer-beads-counters',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Prayer', 'Remembrance', 'Contemplation'],
  'Global',
  ARRAY['Ceramic', 'Electronic Components'],
  ARRAY['Handcrafted'],
  ARRAY['Daily Practice'],
  ARRAY['Prayer Space', 'Home', 'Study Area'],
  'Dedicated Practice',
  '3-4 days',
  'Created for meditative, silent counting without mechanical noise.',
  'Handcrafted with smooth ceramic and sensitive touch technology.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Silent Electronic Counting Beads',
  'Set of electronic beads that track count internally. Check total on any bead. No sound, no light, just quiet confirmation.',
  '54.99',
  ARRAY['https://images.pexels.com/photos/5623016/pexels-photo-5623016.jpeg'],
  'prayer-remembrance',
  'prayer-beads-counters',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Prayer', 'Remembrance', 'Devotion'],
  'Global',
  ARRAY['Wood', 'Electronic Components', 'Cord'],
  ARRAY['Hand-assembled'],
  ARRAY['Daily Practice'],
  ARRAY['Prayer Space', 'Home'],
  'Dedicated Practice',
  '7-10 days',
  'Made for deep prayer practice with the assurance of accurate counting.',
  'Hand-assembled with precision electronics and natural wood beads.'
);
