/*
  # Add Travel Journals & Digital Travel Products

  1. Products Added
    - 4 hand-bound travel journals
    - 5 digital/electronic travel items (note: some already added in previous migrations)

  2. Category Placement
    - Journals: learning-scripture / study-aids
    - Digital products: gifts-collections / gift-sets-bundles

  3. Design Principles
    - Physical journals for documenting sacred journeys
    - Digital tools support offline travel practice
    - Faith-neutral, suitable for all Abrahamic traditions
*/

INSERT INTO products (
  vendor_id,
  title,
  description,
  price,
  images,
  layer1_category_slug,
  layer2_category_slug,
  traditions,
  purposes,
  origin,
  materials,
  handmade_process,
  life_moments,
  use_contexts,
  practice_depth,
  time_to_make,
  purpose_description,
  artisan_info
) VALUES
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Hand-bound Pilgrimage Journal',
  'Beautiful hand-bound journal for recording sacred journey. Thick paper, leather cover. Prompts for reflection, space for writing. Documents spiritual growth during pilgrimage.',
  '44.99',
  ARRAY['https://images.pexels.com/photos/4207892/pexels-photo-4207892.jpeg'],
  'learning-scripture',
  'study-aids',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Reflection', 'Writing', 'Pilgrimage', 'Memory'],
  'Global',
  ARRAY['Leather', 'Recycled Paper', 'Cotton Thread'],
  ARRAY['Hand-bound'],
  ARRAY['Pilgrimage'],
  ARRAY['Travel', 'Home'],
  'Dedicated Practice',
  '5-7 days',
  'Created to document and honor the spiritual journey of pilgrimage.',
  'Hand-bound using traditional bookbinding techniques with quality materials.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Travel Reflection Notebook',
  'Compact notebook for daily reflections during travel. Fits in pocket, durable binding. Blank pages for freedom of expression. Cross-tradition journaling tool.',
  '18.99',
  ARRAY['https://images.pexels.com/photos/4207892/pexels-photo-4207892.jpeg'],
  'learning-scripture',
  'study-aids',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Reflection', 'Writing', 'Travel', 'Daily Wisdom'],
  'Global',
  ARRAY['Recycled Paper', 'Cardstock Cover'],
  ARRAY['Hand-bound'],
  ARRAY['Pilgrimage', 'Daily Practice'],
  ARRAY['Travel'],
  'Everyday Use',
  '2-3 days',
  'Designed for capturing daily insights and reflections during travel.',
  'Hand-bound with durable materials sized for easy travel carrying.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Journey Log Book',
  'Structured log for pilgrimage journey. Sections for dates, locations, reflections, prayers. Helps organize experience. Becomes treasured record.',
  '29.99',
  ARRAY['https://images.pexels.com/photos/4207892/pexels-photo-4207892.jpeg'],
  'learning-scripture',
  'study-aids',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Organization', 'Writing', 'Pilgrimage', 'Memory'],
  'Global',
  ARRAY['Recycled Paper', 'Cloth Cover', 'Cotton Thread'],
  ARRAY['Hand-bound'],
  ARRAY['Pilgrimage'],
  ARRAY['Travel', 'Home'],
  'Dedicated Practice',
  '4-6 days',
  'Made to help structure and preserve pilgrimage memories systematically.',
  'Hand-bound with thoughtfully designed prompts and sections.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Sacred Route Notes Journal',
  'Journal specifically for documenting sacred routes and sites. Maps section, notes pages, reflection prompts. For those who walk with attention.',
  '34.99',
  ARRAY['https://images.pexels.com/photos/4207892/pexels-photo-4207892.jpeg'],
  'learning-scripture',
  'study-aids',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Writing', 'Learning', 'Pilgrimage', 'Geography'],
  'Global',
  ARRAY['Recycled Paper', 'Leather Cover', 'Cotton Thread'],
  ARRAY['Hand-bound'],
  ARRAY['Pilgrimage'],
  ARRAY['Travel', 'Study Area'],
  'Dedicated Practice',
  '5-7 days',
  'Created for mindful documentation of sacred geography and journey.',
  'Hand-bound with space for both visual and written documentation.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Travel Prayer Timer (Offline)',
  'Compact electronic timer designed for travel. Multiple time zones, no internet. Battery lasts entire pilgrimage. Silent or gentle vibration alerts.',
  '29.99',
  ARRAY['https://images.pexels.com/photos/5623016/pexels-photo-5623016.jpeg'],
  'gifts-collections',
  'gift-sets-bundles',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Prayer', 'Time Management', 'Travel', 'Pilgrimage'],
  'Global',
  ARRAY['Aluminum', 'Electronic Components'],
  ARRAY['Small Batch'],
  ARRAY['Pilgrimage', 'Daily Practice'],
  ARRAY['Travel'],
  'Everyday Use',
  '2-3 days',
  'Designed to support prayer rhythm across time zones during travel.',
  'Built with long battery life and multi-zone capability.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Portable Silence Bell (Travel)',
  'Ultra-compact electronic bell for contemplative practice. Single gentle tone, volume adjustable. Fits anywhere, battery lasts months.',
  '26.99',
  ARRAY['https://images.pexels.com/photos/6216589/pexels-photo-6216589.jpeg'],
  'gifts-collections',
  'gift-sets-bundles',
  ARRAY['Abrahamic Shared', 'Christianity', 'Judaism', 'Islam'],
  ARRAY['Reflection', 'Contemplation', 'Travel', 'Pilgrimage'],
  'Global',
  ARRAY['Metal', 'Electronic Components'],
  ARRAY['Small Batch'],
  ARRAY['Pilgrimage', 'Daily Practice'],
  ARRAY['Travel', 'Prayer Space'],
  'Everyday Use',
  '2-3 days',
  'Created for marking contemplative moments during sacred travel.',
  'Compact design with quality audio components and long battery life.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Pocket Direction Finder (Electronic)',
  'Electronic compass the size of a coin. Always accurate, no calibration needed. Clips to keychain. Essential for directional prayer during pilgrimage.',
  '18.99',
  ARRAY['https://images.pexels.com/photos/6253618/pexels-photo-6253618.jpeg'],
  'gifts-collections',
  'gift-sets-bundles',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Prayer', 'Orientation', 'Travel', 'Pilgrimage'],
  'Global',
  ARRAY['Aluminum', 'Electronic Components'],
  ARRAY['Small Batch'],
  ARRAY['Pilgrimage', 'Daily Practice'],
  ARRAY['Travel'],
  'Everyday Use',
  '1-2 days',
  'Made for convenient, always-available prayer orientation during travel.',
  'Ultra-compact with reliable electronic compass and long battery life.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Digital Pilgrimage Journal (PDF)',
  'Downloadable PDF journal for pilgrimage. Printable pages with reflection prompts. Bring as many copies as needed. One purchase, lifetime access.',
  '19.99',
  ARRAY['https://images.pexels.com/photos/4207892/pexels-photo-4207892.jpeg'],
  'gifts-collections',
  'gift-sets-bundles',
  ARRAY['Abrahamic Shared', 'Islam', 'Christianity', 'Judaism'],
  ARRAY['Writing', 'Reflection', 'Pilgrimage', 'Organization'],
  'Digital',
  ARRAY['Digital PDF'],
  ARRAY['Digital'],
  ARRAY['Pilgrimage'],
  ARRAY['Travel', 'Home'],
  'Dedicated Practice',
  'Instant',
  'Designed for documenting sacred journeys with structured prompts.',
  'Thoughtfully designed with space for reflection across faith traditions.'
),
(
  '6780a658-1c13-4462-8411-3e09c5f6b0da',
  'Guided Travel Reflection Audio',
  'Audio reflections for pilgrimage journey. Listen during travel or before prayer. No instructions, just contemplative prompts. Download and keep. 10 tracks, 15 minutes each.',
  '24.99',
  ARRAY['https://images.pexels.com/photos/6216589/pexels-photo-6216589.jpeg'],
  'gifts-collections',
  'gift-sets-bundles',
  ARRAY['Abrahamic Shared', 'Christianity', 'Judaism', 'Islam'],
  ARRAY['Reflection', 'Contemplation', 'Pilgrimage', 'Travel'],
  'Digital',
  ARRAY['Digital Audio'],
  ARRAY['Digital'],
  ARRAY['Pilgrimage'],
  ARRAY['Travel', 'Home'],
  'Dedicated Practice',
  'Instant',
  'Created to deepen pilgrimage experience through contemplative listening.',
  'Recorded with care to honor the sacred nature of pilgrimage across traditions.'
);
